// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBitrixTime = "bitrix_times"

// BitrixTime mapped from table <bitrix_times>
type BitrixTime struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID    int64     `gorm:"column:user_id;not null" json:"user_id"`
	Begin     time.Time `gorm:"column:begin" json:"begin"`
	End       time.Time `gorm:"column:end" json:"end"`
	Duration  int64     `gorm:"column:duration;not null" json:"duration"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName BitrixTime's table name
func (*BitrixTime) TableName() string {
	return TableNameBitrixTime
}
