// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCalendarDay = "calendar_days"

// CalendarDay mapped from table <calendar_days>
type CalendarDay struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Day       time.Time `gorm:"column:day;not null" json:"day"`
	Type      int32     `gorm:"column:type;not null" json:"type"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName CalendarDay's table name
func (*CalendarDay) TableName() string {
	return TableNameCalendarDay
}
