// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameComment = "comments"

// Comment mapped from table <comments>
type Comment struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID        int64     `gorm:"column:user_id;not null" json:"user_id"`
	Content       string    `gorm:"column:content;not null" json:"content"`
	CreatedAt     time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at" json:"updated_at"`
	EditorVersion int64     `gorm:"column:editor_version;not null" json:"editor_version"`
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
