// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameContainComment = "contain_comments"

// ContainComment mapped from table <contain_comments>
type ContainComment struct {
	ID                 int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CommentID          int64  `gorm:"column:comment_id;not null" json:"comment_id"`
	ContainCommentID   int64  `gorm:"column:contain_comment_id;not null" json:"contain_comment_id"`
	ContainCommentType string `gorm:"column:contain_comment_type;not null" json:"contain_comment_type"`
}

// TableName ContainComment's table name
func (*ContainComment) TableName() string {
	return TableNameContainComment
}
