// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameContainFile = "contain_files"

// ContainFile mapped from table <contain_files>
type ContainFile struct {
	ID              int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	FileID          int64  `gorm:"column:file_id;not null" json:"file_id"`
	ContainFileID   int64  `gorm:"column:contain_file_id;not null" json:"contain_file_id"`
	ContainFileType string `gorm:"column:contain_file_type;not null" json:"contain_file_type"`
}

// TableName ContainFile's table name
func (*ContainFile) TableName() string {
	return TableNameContainFile
}
