// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameEstimate = "estimates"

// Estimate mapped from table <estimates>
type Estimate struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name      string         `gorm:"column:name;not null" json:"name"`
	ProjectID int64          `gorm:"column:project_id;not null" json:"project_id"`
	UserID    int64          `gorm:"column:user_id" json:"user_id"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Estimate's table name
func (*Estimate) TableName() string {
	return TableNameEstimate
}
