// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEstimateItem = "estimate_items"

// EstimateItem mapped from table <estimate_items>
type EstimateItem struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	EstimateID int64     `gorm:"column:estimate_id;not null" json:"estimate_id"`
	RoleID     int64     `gorm:"column:role_id;not null" json:"role_id"`
	TimeH      float64   `gorm:"column:time_h;not null;default:0.00" json:"time_h"`
	Rate       float64   `gorm:"column:rate;not null;default:0.00" json:"rate"`
	CreatedAt  time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName EstimateItem's table name
func (*EstimateItem) TableName() string {
	return TableNameEstimateItem
}
