// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGradeItem = "grade_items"

// GradeItem mapped from table <grade_items>
type GradeItem struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	GradeID     int64     `gorm:"column:grade_id;not null" json:"grade_id"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	Description string    `gorm:"column:description" json:"description"`
	CreatedAt   time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName GradeItem's table name
func (*GradeItem) TableName() string {
	return TableNameGradeItem
}
