// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGradeItemTask = "grade_item_task"

// GradeItemTask mapped from table <grade_item_task>
type GradeItemTask struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TaskID       int64     `gorm:"column:task_id;not null" json:"task_id"`
	GradeItemID  int64     `gorm:"column:grade_item_id;not null" json:"grade_item_id"`
	Rating       int32     `gorm:"column:rating;not null" json:"rating"`
	UserID       int64     `gorm:"column:user_id;comment:Создатель пункта" json:"user_id"`             // Создатель пункта
	RaterID      int64     `gorm:"column:rater_id;comment:Оценщик пункта" json:"rater_id"`             // Оценщик пункта
	GradedUserID int64     `gorm:"column:graded_user_id;comment:Кого оценивают" json:"graded_user_id"` // Кого оценивают
	Comment      string    `gorm:"column:comment" json:"comment"`
	CreatedAt    time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName GradeItemTask's table name
func (*GradeItemTask) TableName() string {
	return TableNameGradeItemTask
}
