// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameHistory = "histories"

// History mapped from table <histories>
type History struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RelatedID   int64     `gorm:"column:related_id;not null" json:"related_id"`
	RelatedType string    `gorm:"column:related_type;not null" json:"related_type"`
	UserID      int64     `gorm:"column:user_id" json:"user_id"`
	Content     string    `gorm:"column:content" json:"content"`
	CreatedAt   time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName History's table name
func (*History) TableName() string {
	return TableNameHistory
}
