// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOutgoingWebhookProject = "outgoing_webhook_project"

// OutgoingWebhookProject mapped from table <outgoing_webhook_project>
type OutgoingWebhookProject struct {
	ID                int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OutgoingWebhookID int64 `gorm:"column:outgoing_webhook_id;not null" json:"outgoing_webhook_id"`
	ProjectID         int64 `gorm:"column:project_id;not null" json:"project_id"`
}

// TableName OutgoingWebhookProject's table name
func (*OutgoingWebhookProject) TableName() string {
	return TableNameOutgoingWebhookProject
}
