// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/gorm"
	"time"
)

const TableNameProjectUser = "project_user"

// ProjectUser mapped from table <project_user>
type ProjectUser struct {
	gorm.Model
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID    int64     `gorm:"column:user_id;not null" json:"user_id"`
	ProjectID int64     `gorm:"column:project_id;not null" json:"project_id"`
	RoleID    int64     `gorm:"column:role_id;not null" json:"role_id"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName ProjectUser's table name
func (*ProjectUser) TableName() string {
	return TableNameProjectUser
}
