// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameReportQueue = "report_queues"

// ReportQueue mapped from table <report_queues>
type ReportQueue struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Status    int32     `gorm:"column:status;not null" json:"status"`
	URL       string    `gorm:"column:url" json:"url"`
	Error     string    `gorm:"column:error;not null" json:"error"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName ReportQueue's table name
func (*ReportQueue) TableName() string {
	return TableNameReportQueue
}
