// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTagUser = "tag_user"

// TagUser mapped from table <tag_user>
type TagUser struct {
	ID     int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID int64 `gorm:"column:user_id;not null" json:"user_id"`
	TagID  int64 `gorm:"column:tag_id;not null" json:"tag_id"`
}

// TableName TagUser's table name
func (*TagUser) TableName() string {
	return TableNameTagUser
}
