// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTag = "tags"

// Tag mapped from table <tags>
type Tag struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
	Tag       string    `gorm:"column:tag;not null" json:"tag"`
	ColorBg   string    `gorm:"column:color_bg;not null;default:17a2b8" json:"color_bg"`
	ColorFg   string    `gorm:"column:color_fg;not null;default:ffffff" json:"color_fg"`
}

// TableName Tag's table name
func (*Tag) TableName() string {
	return TableNameTag
}
