// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTaskGradeUser = "task_grade_users"

// TaskGradeUser mapped from table <task_grade_users>
type TaskGradeUser struct {
	ID       int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID   int64 `gorm:"column:user_id;not null" json:"user_id"`
	TaskID   int64 `gorm:"column:task_id;not null" json:"task_id"`
	Required bool  `gorm:"column:required;not null" json:"required"`
}

// TableName TaskGradeUser's table name
func (*TaskGradeUser) TableName() string {
	return TableNameTaskGradeUser
}
