// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTaskStat = "task_stats"

// TaskStat mapped from table <task_stats>
type TaskStat struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	WorkerID       int64     `gorm:"column:worker_id;not null" json:"worker_id"`
	TaskID         int64     `gorm:"column:task_id;not null" json:"task_id"`
	ProjectID      int64     `gorm:"column:project_id;not null" json:"project_id"`
	StageID        int64     `gorm:"column:stage_id;not null" json:"stage_id"`
	TaskWordCount  int64     `gorm:"column:task_word_count;not null" json:"task_word_count"`
	EstimateWorker int64     `gorm:"column:estimate_worker;not null" json:"estimate_worker"`
	WorkWorker     int64     `gorm:"column:work_worker;not null" json:"work_worker"`
	WorkTotal      int64     `gorm:"column:work_total;not null" json:"work_total"`
	WorkDev        int64     `gorm:"column:work_dev;not null" json:"work_dev"`
	WorkLead       int64     `gorm:"column:work_lead;not null" json:"work_lead"`
	WorkTester     int64     `gorm:"column:work_tester;not null" json:"work_tester"`
	WorkManager    int64     `gorm:"column:work_manager;not null" json:"work_manager"`
	WorkBugTotal   int64     `gorm:"column:work_bug_total;not null" json:"work_bug_total"`
	TestBugTotal   int64     `gorm:"column:test_bug_total;not null" json:"test_bug_total"`
	WorkDoneTime   int64     `gorm:"column:work_done_time;not null" json:"work_done_time"`
	BugCount       int64     `gorm:"column:bug_count;not null" json:"bug_count"`
	CreatedAt      time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName TaskStat's table name
func (*TaskStat) TableName() string {
	return TableNameTaskStat
}
