// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTask = "tasks"

// Task mapped from table <tasks>
type Task struct {
	ID                   int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name                 string         `gorm:"column:name;not null" json:"name"`
	Description          string         `gorm:"column:description" json:"description"`
	CreatedByID          int64          `gorm:"column:created_by_id;not null" json:"created_by_id"`
	ProjectID            int64          `gorm:"column:project_id;not null" json:"project_id"`
	StageID              int64          `gorm:"column:stage_id;not null" json:"stage_id"`
	TaskTypeID           int64          `gorm:"column:task_type_id;not null" json:"task_type_id"`
	ComponentID          int64          `gorm:"column:component_id" json:"component_id"`
	PriorityID           int64          `gorm:"column:priority_id;not null" json:"priority_id"`
	ReleaseID            int64          `gorm:"column:release_id" json:"release_id"`
	EstimateCost         int64          `gorm:"column:estimate_cost" json:"estimate_cost"`
	EstimateWorker       int64          `gorm:"column:estimate_worker" json:"estimate_worker"`
	Deadline             time.Time      `gorm:"column:deadline" json:"deadline"`
	LayoutLink           string         `gorm:"column:layout_link" json:"layout_link"`
	MarkupLink           string         `gorm:"column:markup_link" json:"markup_link"`
	DevLink              string         `gorm:"column:dev_link" json:"dev_link"`
	DeletedAt            gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt            time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt            time.Time      `gorm:"column:updated_at" json:"updated_at"`
	ExternalSystemTypeID int64          `gorm:"column:external_system_type_id" json:"external_system_type_id"`
	ExternalSystemTaskID string         `gorm:"column:external_system_task_id" json:"external_system_task_id"`
	EpicID               int64          `gorm:"column:epic_id" json:"epic_id"`
	BugReturnCount       int64          `gorm:"column:bug_return_count;not null" json:"bug_return_count"`
	Begin                time.Time      `gorm:"column:begin" json:"begin"`
	End                  time.Time      `gorm:"column:end" json:"end"`
	DateStart            time.Time      `gorm:"column:date_start" json:"date_start"`
	DateEnd              time.Time      `gorm:"column:date_end" json:"date_end"`
	Rank                 string         `gorm:"column:rank;not null;default:abc" json:"rank"`
	EditorVersion        int64          `gorm:"column:editor_version;not null" json:"editor_version"`
}

// TableName Task's table name
func (*Task) TableName() string {
	return TableNameTask
}
