// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTaskHistory = "task_histories"

// TaskHistory mapped from table <task_histories>
type TaskHistory struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
	TaskID    int64     `gorm:"column:task_id;not null" json:"task_id"`
	Data      string    `gorm:"column:data;not null" json:"data"`
}

// TableName TaskHistory's table name
func (*TaskHistory) TableName() string {
	return TableNameTaskHistory
}
