// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTaskBlock = "task_block"

// TaskBlock mapped from table <task_block>
type TaskBlock struct {
	ID          int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TaskIDBlock int64 `gorm:"column:task_id_block;not null" json:"task_id_block"`
	TaskID      int64 `gorm:"column:task_id;not null" json:"task_id"`
}

// TableName TaskBlock's table name
func (*TaskBlock) TableName() string {
	return TableNameTaskBlock
}
