// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTaskRelated = "task_related"

// TaskRelated mapped from table <task_related>
type TaskRelated struct {
	ID        int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TaskIDRel int64 `gorm:"column:task_id_rel;not null" json:"task_id_rel"`
	TaskID    int64 `gorm:"column:task_id;not null" json:"task_id"`
}

// TableName TaskRelated's table name
func (*TaskRelated) TableName() string {
	return TableNameTaskRelated
}
