// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserAbsence = "user_absences"

// UserAbsence mapped from table <user_absences>
type UserAbsence struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name         string    `gorm:"column:name;not null" json:"name"`
	UserID       int64     `gorm:"column:user_id;not null" json:"user_id"`
	BitrixID     int64     `gorm:"column:bitrix_id;not null" json:"bitrix_id"`
	BitrixUserID int64     `gorm:"column:bitrix_user_id;not null" json:"bitrix_user_id"`
	DateFrom     time.Time `gorm:"column:date_from;not null" json:"date_from"`
	DateTo       time.Time `gorm:"column:date_to;not null" json:"date_to"`
	FromHr       bool      `gorm:"column:from_hr;not null" json:"from_hr"`
	CreatedAt    time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName UserAbsence's table name
func (*UserAbsence) TableName() string {
	return TableNameUserAbsence
}
