// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWebsocketsStatisticsEntry = "websockets_statistics_entries"

// WebsocketsStatisticsEntry mapped from table <websockets_statistics_entries>
type WebsocketsStatisticsEntry struct {
	ID                    int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AppID                 string    `gorm:"column:app_id;not null" json:"app_id"`
	PeakConnectionCount   int32     `gorm:"column:peak_connection_count;not null" json:"peak_connection_count"`
	WebsocketMessageCount int32     `gorm:"column:websocket_message_count;not null" json:"websocket_message_count"`
	APIMessageCount       int32     `gorm:"column:api_message_count;not null" json:"api_message_count"`
	CreatedAt             time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt             time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName WebsocketsStatisticsEntry's table name
func (*WebsocketsStatisticsEntry) TableName() string {
	return TableNameWebsocketsStatisticsEntry
}
