// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWork = "works"

// Work mapped from table <works>
type Work struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TaskID    int64     `gorm:"column:task_id;not null" json:"task_id"`
	UserID    int64     `gorm:"column:user_id;not null" json:"user_id"`
	Time      int64     `gorm:"column:time;not null" json:"time"`
	Begin     time.Time `gorm:"column:begin" json:"begin"`
	End       time.Time `gorm:"column:end" json:"end"`
	Overtime  bool      `gorm:"column:overtime;not null" json:"overtime"`
	Comment   string    `gorm:"column:comment" json:"comment"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName Work's table name
func (*Work) TableName() string {
	return TableNameWork
}
